import type { JobPlatform, JobWorkMode } from "@applywise/types";
import { DEMO_NOTICE } from "../connectors/seeded";
import type { RawImportedJob } from "../connectors/types";

/**
 * DEMO CONTENT for the automation demo provider. Every company, job, URL and email address below is fictional:
 * career sites use the reserved .example TLD, HR addresses the reserved .test TLD, and the two browser-executor
 * jobs point at the local demo ATS pages served by the web app under /demo/ats/*.
 *
 * The catalogue is tuned against the seeded demo candidate (React/TypeScript frontend engineer, 5 years,
 * Bengaluru / Remote - India) so the REAL matching engine spreads it over three bands - verify with
 * `cd packages/database && npx tsx scripts/demo-score-distribution.ts`:
 *  - high:   score >= 90 (auto-apply candidates, each carrying one scripted outcome)
 *  - medium: 70-89 (review / recommend)
 *  - low:    below 70 (Java backend, data, DevOps, QA, native mobile, sales, ...)
 * Nothing here is random: the same `now` always yields the same jobs.
 */

export const DEMO_SCENARIOS = [
  /** Submits successfully on the first attempt. */
  "auto_success",
  /** First attempt fails with a retryable error, the retry succeeds. */
  "transient_failure",
  /** Fails permanently (e.g. the posting closed). */
  "permanent_failure",
  /** The application page shows a CAPTCHA -> MANUAL_ACTION_REQUIRED (never bypassed). */
  "captcha",
  "login_required",
  "mfa",
  /** The provider asks a required question the candidate never answered -> NEEDS_INFORMATION. */
  "unknown_question",
  /** Submits, then the status sync reports these outcomes (and a simulated recruiter email). */
  "assessment",
  "interview",
  "rejection",
  "offer",
  /** Simulates a platform without automatic application support (LinkedIn/Naukri-like) -> manual handoff. */
  "manual_only",
] as const;
export type DemoScenario = (typeof DEMO_SCENARIOS)[number];

export function isDemoScenario(value: unknown): value is DemoScenario {
  return typeof value === "string" && (DEMO_SCENARIOS as readonly string[]).includes(value);
}

/** "api": the demo provider's simulated API. "browser": the demo ATS page, filled by the browser executor. */
export type DemoChannel = "api" | "browser";

export type DemoTier = "high" | "medium" | "low";

export interface DemoJobsOptions {
  /** Base URL of the web app (demo ATS pages live under /demo/ats). */
  appUrl: string;
  /** Deterministic "now" (defaults to the current time). */
  now?: Date;
  /** Number of distinct jobs before duplicates are added (default 110, at most the catalogue size). */
  count?: number;
}

// ---------------------------------------------------------------- simulated sources

export type DemoSourceId = "linkedin" | "naukri" | "indeed" | "wellfound" | "greenhouse" | "lever" | "careers";

interface DemoSource {
  label: string;
  platform: JobPlatform;
  /** Public listing URL on the simulated source (reserved .example hosts only). */
  listingUrl(job: { key: string; id: number; slug: string }): string;
}

export const DEMO_SOURCES: Record<DemoSourceId, DemoSource> = {
  linkedin: { label: "LinkedIn job alert (demo)", platform: "LINKEDIN", listingUrl: (j) => `https://demo-linkedin.example/jobs/view/${j.id}` },
  naukri: { label: "Naukri (demo)", platform: "NAUKRI", listingUrl: (j) => `https://demo-naukri.example/job-listings/${j.key}-${j.id}` },
  indeed: { label: "Indeed (demo)", platform: "INDEED", listingUrl: (j) => `https://demo-indeed.example/viewjob?jk=${j.id}` },
  wellfound: { label: "Wellfound (demo)", platform: "WELLFOUND", listingUrl: (j) => `https://demo-wellfound.example/jobs/${j.id}-${j.key}` },
  greenhouse: { label: "Greenhouse board (demo)", platform: "GREENHOUSE", listingUrl: (j) => `https://demo-greenhouse.example/${j.slug}/jobs/${j.id}` },
  lever: { label: "Lever board (demo)", platform: "LEVER", listingUrl: (j) => `https://demo-lever.example/${j.slug}/${j.id}` },
  careers: { label: "Company careers (demo)", platform: "COMPANY_CAREER_PAGE", listingUrl: (j) => `https://careers.${j.slug}.example/jobs/${j.id}` },
};

/** Simulated platforms without automatic application support: their medium/low jobs are manual_only. */
const MANUAL_SOURCES = new Set<DemoSourceId>(["linkedin", "naukri"]);

// ---------------------------------------------------------------- catalogue

interface AutomationJobSpec {
  key: string;
  tier: DemoTier;
  title: string;
  company: string;
  about: string;
  locations: string[];
  workMode: JobWorkMode;
  yoe: [number, number];
  /** Required skills; "(must)" marks a mandatory one. */
  required: string[];
  preferred: string[];
  responsibilities: string[];
  source: DemoSourceId;
  /** Defaults: manual_only for LinkedIn/Naukri sources, else auto_success. */
  scenario?: DemoScenario;
  channel?: DemoChannel;
  postedDaysAgo: number;
  salaryLpa?: [number, number];
  /** Apply by email to hiring@<company-slug>.test (applyMethod EMAIL). */
  hrEmail?: boolean;
  screening?: string[];
  extras?: string[];
  /** The same posting also found on these simulated sources (cross-provider duplicates). */
  alsoOn?: DemoSourceId[];
}

const HIGH: AutomationJobSpec[] = [
  {
    key: "aw-reelcraft-timeline",
    tier: "high",
    title: "Senior Frontend Engineer - Video Timeline",
    company: "Reelcraft Studio",
    about: "Reelcraft Studio builds a browser-based video editor used by independent creators across India.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [4, 7],
    required: ["React (must)", "TypeScript (must)", "multi-track timeline", "Canvas API"],
    preferred: ["Web Workers", "WebCodecs"],
    responsibilities: [
      "Own the multi-track video timeline, trimming and drag-and-drop clip tools",
      "Keep canvas preview rendering smooth on long creator projects",
      "Design undo/redo for complex editing workflows",
    ],
    source: "greenhouse",
    scenario: "auto_success",
    channel: "browser",
    postedDaysAgo: 1,
    salaryLpa: [30, 45],
    screening: ["What is your expected CTC?", "How many years of professional experience do you have?"],
    alsoOn: ["linkedin"],
  },
  {
    key: "aw-framewise-creator-editor",
    tier: "high",
    title: "Frontend Engineer - Creator Editor",
    company: "Framewise",
    about: "Framewise helps short-form video creators storyboard, cut and publish from the browser.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["React (must)", "TypeScript", "Canvas API", "rendering performance"],
    preferred: ["Web Workers"],
    responsibilities: [
      "Build the canvas-based editor creators use to storyboard short videos",
      "Profile and fix rendering hot spots in the editor",
      "Work with designers on editing interactions",
    ],
    source: "greenhouse",
    scenario: "captcha",
    channel: "browser",
    postedDaysAgo: 2,
    salaryLpa: [28, 40],
    screening: ["What is your expected CTC?"],
  },
  {
    key: "aw-clipmint-video-uploads",
    tier: "high",
    title: "React Developer - Video Uploads",
    company: "Clipmint",
    about: "Clipmint is a video hosting platform for coaching businesses.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React (must)", "TypeScript", "resumable uploads", "Amazon S3"],
    preferred: ["Web Workers"],
    responsibilities: [
      "Build resumable chunked upload flows for multi-GB video files",
      "Show upload and processing progress in the media dashboard",
      "Write unit tests for upload edge cases",
    ],
    source: "linkedin",
    scenario: "manual_only",
    postedDaysAgo: 3,
    salaryLpa: [22, 32],
    alsoOn: ["naukri"],
  },
  {
    key: "aw-dashcraft-senior-react",
    tier: "high",
    title: "Senior React Developer - Analytics Dashboard",
    company: "Dashcraft",
    about: "Dashcraft is a B2B analytics product for operations teams.",
    locations: ["Bengaluru"],
    workMode: "onsite",
    yoe: [6, 9],
    required: ["React (must)", "TypeScript (must)", "Redux", "rendering performance"],
    preferred: ["Jest", "React Testing Library"],
    responsibilities: [
      "Build the SaaS analytics dashboard used by operations teams",
      "Virtualise large tables and charts to keep the dashboard fast",
      "Mentor two frontend engineers",
    ],
    source: "naukri",
    scenario: "manual_only",
    postedDaysAgo: 5,
    salaryLpa: [28, 38],
  },
  {
    key: "aw-pipeflow-workflow-builder",
    tier: "high",
    title: "Frontend Engineer - Workflow Builder",
    company: "Pipeflow",
    about: "Pipeflow automates approvals and hand-offs for finance and operations teams.",
    locations: ["Bengaluru", "Remote - India"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React (must)", "TypeScript", "drag-and-drop", "state management"],
    preferred: ["Playwright", "Jest"],
    responsibilities: [
      "Build the drag-and-drop workflow builder at the heart of our B2B SaaS product",
      "Model complex workflow state with undo/redo",
      "Write end-to-end tests with Playwright",
    ],
    source: "lever",
    scenario: "transient_failure",
    postedDaysAgo: 2,
    salaryLpa: [26, 36],
    alsoOn: ["naukri"],
  },
  {
    key: "aw-cutline-review-ui",
    tier: "high",
    title: "UI Engineer - Video Review",
    company: "Cutline",
    about: "Cutline gives post-production teams frame-accurate review and approval tools.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [4, 7],
    required: ["React (must)", "TypeScript", "Canvas API", "Web Workers"],
    preferred: ["WebCodecs"],
    responsibilities: [
      "Build frame-accurate video review and annotation tools",
      "Render comments on a canvas overlay synced to the video timeline",
      "Keep playback responsive with background workers",
    ],
    source: "careers",
    scenario: "permanent_failure",
    postedDaysAgo: 8,
    salaryLpa: [27, 38],
  },
  {
    key: "aw-streamdesk-studio",
    tier: "high",
    title: "Frontend Developer - Streaming Studio",
    company: "Streamdesk",
    about: "Streamdesk is a live-streaming studio for educators and creators.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["React", "TypeScript", "state management", "REST APIs"],
    preferred: ["Jest"],
    responsibilities: [
      "Build the live streaming studio dashboard for creators",
      "Integrate REST APIs for scheduling and analytics",
      "Improve reliability of the stream preview",
    ],
    source: "indeed",
    scenario: "login_required",
    postedDaysAgo: 4,
    salaryLpa: [24, 34],
  },
  {
    key: "aw-motionlab-motion-editor",
    tier: "high",
    title: "Senior Frontend Engineer - Motion Editor",
    company: "Motionlab",
    about: "Motionlab makes a web-based motion graphics tool for marketing teams.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [5, 8],
    required: ["React (must)", "TypeScript (must)", "Canvas API", "rendering performance"],
    preferred: ["Web Workers", "Zustand"],
    responsibilities: [
      "Build a keyframe animation editor for motion designers",
      "Optimise canvas rendering for complex animation timelines",
      "Shape the editor's state architecture",
    ],
    source: "wellfound",
    scenario: "mfa",
    postedDaysAgo: 6,
    salaryLpa: [34, 48],
  },
  {
    key: "aw-shotlist-creator-tools",
    tier: "high",
    title: "Frontend Engineer - Creator Tools",
    company: "Shotlist",
    about: "Shotlist is a planning app for video production crews, with teams in Bengaluru and Singapore.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["React (must)", "TypeScript", "drag-and-drop", "Jest"],
    preferred: ["Playwright"],
    responsibilities: [
      "Build planning tools that help video creators organise shoots",
      "Ship drag-and-drop boards and timeline views",
      "Collaborate with the Singapore product team",
    ],
    source: "greenhouse",
    scenario: "unknown_question",
    postedDaysAgo: 3,
    salaryLpa: [25, 35],
  },
  {
    key: "aw-vidnote-fullstack",
    tier: "high",
    title: "Full-Stack Engineer (React + Node.js)",
    company: "Vidnote",
    about: "Vidnote turns recorded meetings and lectures into searchable video notes.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [4, 7],
    required: ["React (must)", "Node.js", "TypeScript", "REST APIs"],
    preferred: ["Amazon S3", "resumable uploads"],
    responsibilities: [
      "Build video note-taking features across the React app and Node.js services",
      "Design REST endpoints for media uploads",
      "Own features end to end, from schema to UI",
    ],
    source: "lever",
    scenario: "unknown_question",
    postedDaysAgo: 5,
    salaryLpa: [28, 40],
  },
  {
    key: "aw-storyloop-storyboard",
    tier: "high",
    title: "Frontend Engineer - Storyboard Editor",
    company: "Storyloop",
    about: "Storyloop builds pre-production software for animation studios.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "TypeScript", "Canvas API", "drag-and-drop", "CSS"],
    preferred: ["Web Workers"],
    responsibilities: [
      "Build the storyboard editor used by animation and video teams",
      "Implement drag-and-drop panels and a canvas sketch layer",
      "Keep large boards fast",
    ],
    source: "careers",
    scenario: "assessment",
    postedDaysAgo: 2,
    salaryLpa: [24, 34],
  },
  {
    key: "aw-tasklet-saas-workflows",
    tier: "high",
    title: "React Engineer - SaaS Workflows",
    company: "Tasklet",
    about: "Tasklet is a B2B SaaS platform for field-service companies.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React (must)", "TypeScript", "state management", "unit testing"],
    preferred: ["React Testing Library", "Playwright"],
    responsibilities: [
      "Build workflow automation screens for our B2B SaaS platform",
      "Own state management for multi-step forms",
      "Raise our test coverage",
    ],
    source: "lever",
    scenario: "interview",
    postedDaysAgo: 1,
    salaryLpa: [25, 36],
    alsoOn: ["indeed"],
  },
  {
    key: "aw-podframe-audio-editor",
    tier: "high",
    title: "Senior Frontend Engineer - Podcast Studio",
    company: "Podframe",
    about: "Podframe is a browser-based recording and editing studio for podcasters.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [4, 7],
    required: ["React (must)", "TypeScript", "Web Workers", "rendering performance"],
    preferred: ["WebCodecs"],
    responsibilities: [
      "Build the browser-based podcast and audio editor",
      "Render waveforms and timelines efficiently",
      "Move heavy processing off the main thread",
    ],
    source: "greenhouse",
    scenario: "interview",
    postedDaysAgo: 4,
    salaryLpa: [32, 44],
  },
  {
    key: "aw-gridboard-project-dashboard",
    tier: "high",
    title: "Frontend Developer - Project Dashboard",
    company: "Gridboard",
    about: "Gridboard is project-tracking software for construction firms.",
    locations: ["Bengaluru"],
    workMode: "onsite",
    yoe: [2, 4],
    required: ["React", "TypeScript", "Redux", "Jest"],
    preferred: ["React Testing Library", "Tailwind CSS"],
    responsibilities: [
      "Build the project dashboard for our B2B SaaS customers",
      "Turn complex schedules into clear views",
      "Keep the component library consistent",
    ],
    source: "careers",
    scenario: "rejection",
    postedDaysAgo: 6,
    salaryLpa: [18, 26],
  },
  {
    key: "aw-viewlytics-video-analytics",
    tier: "high",
    title: "UI Developer - Video Analytics",
    company: "Viewlytics",
    about: "Viewlytics measures how audiences watch long-form video.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["React", "TypeScript", "rendering performance", "REST APIs"],
    preferred: ["Jest", "Next.js"],
    responsibilities: [
      "Build video analytics dashboards for media publishers",
      "Keep charts with millions of points fast",
      "Integrate REST APIs for reporting",
    ],
    source: "indeed",
    scenario: "rejection",
    postedDaysAgo: 9,
  },
  {
    key: "aw-lumacut-video-editor",
    tier: "high",
    title: "Senior Frontend Engineer - Video Editor",
    company: "Lumacut",
    about: "Lumacut is a collaborative video editor for marketing teams.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [4, 7],
    required: ["React (must)", "TypeScript (must)", "multi-track timeline", "Canvas API"],
    preferred: ["WebCodecs", "Web Workers"],
    responsibilities: [
      "Lead the video editor's timeline and preview experience",
      "Build frame-accurate trimming tools",
      "Mentor engineers on the editor codebase",
    ],
    source: "wellfound",
    scenario: "offer",
    postedDaysAgo: 3,
    salaryLpa: [36, 50],
  },
  {
    key: "aw-flowkit-automation-builder",
    tier: "high",
    title: "Frontend Engineer - Automation Builder",
    company: "Flowkit",
    about: "Flowkit is a no-code automation platform for small businesses.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React (must)", "TypeScript", "drag-and-drop", "Redux"],
    preferred: ["Jest"],
    responsibilities: [
      "Build the drag-and-drop automation builder for our SaaS workflows product",
      "Design reusable node and connector components",
      "Improve editor performance on large workflows",
    ],
    source: "greenhouse",
    postedDaysAgo: 2,
    salaryLpa: [26, 38],
    screening: ["What is your notice period?"],
    alsoOn: ["wellfound"],
  },
  {
    key: "aw-sceneforge-scene-editor",
    tier: "high",
    title: "Frontend Engineer - Scene Editor",
    company: "Sceneforge",
    about: "Sceneforge makes a 2D scene editor for explainer videos.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 7],
    required: ["React", "TypeScript", "Canvas API", "Web Workers"],
    preferred: ["rendering performance"],
    responsibilities: [
      "Build the scene editor for explainer video creators",
      "Render layered scenes on canvas",
      "Keep exports responsive with background workers",
    ],
    source: "lever",
    postedDaysAgo: 5,
    salaryLpa: [26, 36],
  },
  {
    key: "aw-uploadly-media-uploads",
    tier: "high",
    title: "React Developer - Media Uploads",
    company: "Uploadly",
    about: "Uploadly is upload infrastructure for media-heavy apps.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React (must)", "TypeScript", "chunked uploads", "Amazon S3"],
    preferred: ["Node.js"],
    responsibilities: [
      "Build the upload widget used for large video and media files",
      "Show resumable progress across flaky networks",
      "Document the widget for customers",
    ],
    source: "careers",
    postedDaysAgo: 1,
    salaryLpa: [22, 32],
    screening: ["What is your notice period?", "What is your expected CTC?"],
    alsoOn: ["linkedin"],
  },
  {
    key: "aw-fanfolio-creator-dashboard",
    tier: "high",
    title: "Frontend Engineer - Creator Dashboard",
    company: "Fanfolio",
    about: "Fanfolio helps creators run memberships and paid communities.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["React", "TypeScript", "Redux", "REST APIs", "HTML"],
    preferred: ["Playwright", "Tailwind CSS"],
    responsibilities: [
      "Build the creator dashboard for memberships and payouts",
      "Integrate REST APIs for analytics",
      "Write end-to-end tests for critical flows",
    ],
    source: "wellfound",
    postedDaysAgo: 7,
    salaryLpa: [24, 34],
  },
  {
    key: "aw-captionly-subtitle-editor",
    tier: "high",
    title: "Frontend Engineer - Subtitle Editor",
    company: "Captionly",
    about: "Captionly creates subtitles and translations for video publishers.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React (must)", "TypeScript", "multi-track timeline", "JavaScript"],
    preferred: ["Jest"],
    responsibilities: [
      "Build the subtitle editor synced to the video timeline",
      "Handle undo/redo across editing sessions",
      "Work with linguists on editing shortcuts",
    ],
    source: "indeed",
    postedDaysAgo: 3,
  },
  {
    key: "aw-critiq-design-review",
    tier: "high",
    title: "Senior React Engineer - Design Review Tool",
    company: "Critiq",
    about: "Critiq lets product teams review designs and video frames in one place.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [6, 9],
    required: ["React (must)", "TypeScript (must)", "Canvas API", "drag-and-drop"],
    preferred: ["Web Workers", "Playwright"],
    responsibilities: [
      "Build annotation tools for designs and video frames",
      "Render large boards on canvas",
      "Lead frontend architecture decisions",
    ],
    source: "careers",
    postedDaysAgo: 10,
    salaryLpa: [34, 46],
  },
];

const MEDIUM: AutomationJobSpec[] = [
  {
    key: "aw-paysetu-payments-frontend",
    tier: "medium",
    title: "Frontend Engineer - Payments",
    company: "Paysetu",
    about: "Paysetu builds payment tools for neighbourhood merchants.",
    locations: ["Mumbai"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React (must)", "TypeScript", "Redux", "unit testing"],
    preferred: ["GraphQL"],
    responsibilities: ["Build UPI payment flows for merchant apps", "Own the settlement and refund screens", "Improve test coverage of payment-critical code"],
    source: "indeed",
    postedDaysAgo: 4,
    salaryLpa: [22, 32],
    alsoOn: ["linkedin"],
  },
  {
    key: "aw-bazaarly-checkout",
    tier: "medium",
    title: "React Developer - Checkout",
    company: "Bazaarly",
    about: "Bazaarly is an online marketplace for handmade goods.",
    locations: ["Hyderabad"],
    workMode: "onsite",
    yoe: [2, 5],
    required: ["React", "JavaScript", "CSS", "REST APIs"],
    preferred: ["Next.js"],
    responsibilities: ["Build the cart and checkout experience for our marketplace", "Integrate REST APIs for orders and returns"],
    source: "naukri",
    postedDaysAgo: 6,
    salaryLpa: [14, 22],
    screening: ["Are you an immediate joiner?", "What is your current CTC?"],
  },
  {
    key: "aw-ledgerloop-fullstack",
    tier: "medium",
    title: "Full-Stack Developer (React + Node.js)",
    company: "Ledgerloop",
    about: "Ledgerloop provides working-capital loans to small manufacturers.",
    locations: ["Pune"],
    workMode: "hybrid",
    yoe: [4, 7],
    required: ["React", "Node.js (must)", "TypeScript", "PostgreSQL"],
    preferred: ["Docker", "AWS"],
    responsibilities: ["Build lending workflows across React and Node.js", "Design PostgreSQL schemas for loan data"],
    source: "lever",
    postedDaysAgo: 11,
    salaryLpa: [20, 30],
    alsoOn: ["naukri"],
  },
  {
    key: "aw-trellisworks-staff-frontend",
    tier: "medium",
    title: "Staff Frontend Engineer",
    company: "Trellisworks",
    about: "Trellisworks makes planning software for large retail chains.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [7, 10],
    required: ["React (must)", "TypeScript (must)", "design systems", "rendering performance"],
    preferred: ["web accessibility"],
    responsibilities: ["Set frontend architecture across our SaaS product suite", "Lead the design system and the performance budget"],
    source: "greenhouse",
    postedDaysAgo: 8,
    salaryLpa: [45, 60],
  },
  {
    key: "aw-coinvault-nextjs",
    tier: "medium",
    title: "Next.js Developer",
    company: "Coinvault",
    about: "Coinvault is an investing app for first-time investors.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["Next.js (must)", "React", "TypeScript", "Tailwind CSS"],
    preferred: ["Vitest"],
    responsibilities: ["Build the trading web app's portfolio and order screens", "Ship fast server-rendered pages"],
    source: "wellfound",
    postedDaysAgo: 16,
    salaryLpa: [20, 30],
  },
  {
    key: "aw-medisync-patient-portal",
    tier: "medium",
    title: "Frontend Engineer - Patient Portal",
    company: "Medisync",
    about: "Medisync connects diagnostic labs with patients.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "TypeScript", "web accessibility", "REST APIs"],
    preferred: ["Jest"],
    responsibilities: ["Build the patient portal for appointments and reports", "Meet accessibility standards for patients using screen readers"],
    source: "greenhouse",
    postedDaysAgo: 5,
    screening: ["How many years of experience do you have with React?"],
  },
  {
    key: "aw-learnly-vue",
    tier: "medium",
    title: "Frontend Developer (Vue.js)",
    company: "Learnly",
    about: "Learnly runs live coding classes for school students.",
    locations: ["Bengaluru"],
    workMode: "onsite",
    yoe: [2, 5],
    required: ["Vue.js", "JavaScript", "CSS", "REST APIs"],
    preferred: ["Tailwind CSS"],
    responsibilities: ["Build course pages and quizzes for students", "Improve the learning dashboard"],
    source: "naukri",
    postedDaysAgo: 19,
    salaryLpa: [12, 20],
  },
  {
    key: "aw-cartwise-storefront",
    tier: "medium",
    title: "Senior Frontend Engineer - Storefront",
    company: "Cartwise",
    about: "Cartwise runs storefronts for direct-to-consumer brands.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [5, 8],
    required: ["React (must)", "Next.js (must)", "TypeScript", "GraphQL"],
    preferred: ["Shopify Hydrogen"],
    responsibilities: ["Build fast storefronts for D2C brands", "Own the checkout funnel"],
    source: "lever",
    postedDaysAgo: 3,
    salaryLpa: [30, 42],
    screening: ["Have you shipped a Next.js storefront to production?"],
  },
  {
    key: "aw-shiplane-backend-node",
    tier: "medium",
    title: "Backend Engineer (Node.js)",
    company: "Shiplane",
    about: "Shiplane is a shipping platform for mid-size exporters.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["Node.js (must)", "TypeScript", "PostgreSQL", "REST APIs"],
    preferred: ["Redis", "Kafka"],
    responsibilities: ["Build shipment tracking APIs for our fleet partners", "Scale delivery event processing"],
    source: "indeed",
    postedDaysAgo: 9,
    salaryLpa: [22, 32],
    screening: ["How many years of Node.js experience do you have?"],
  },
  {
    key: "aw-quizzo-react",
    tier: "medium",
    title: "React Developer",
    company: "Quizzo",
    about: "Quizzo makes live quiz games for classrooms.",
    locations: ["Pune"],
    workMode: "onsite",
    yoe: [2, 5],
    required: ["React", "TypeScript", "Redux", "Jest"],
    preferred: ["Cypress"],
    responsibilities: ["Build live quiz games for classrooms", "Work with teachers and students on new formats"],
    source: "careers",
    postedDaysAgo: 2,
    hrEmail: true,
  },
  {
    key: "aw-suraksha-quotes-ui",
    tier: "medium",
    title: "UI Developer - Insurance Quotes",
    company: "Suraksha Digital",
    about: "Suraksha Digital sells simple term and health cover online.",
    locations: ["Bengaluru"],
    workMode: "onsite",
    yoe: [3, 6],
    required: ["React", "JavaScript", "HTML", "CSS"],
    preferred: ["Angular"],
    responsibilities: ["Build insurance quote and claims journeys", "Make long forms accessible and fast"],
    source: "careers",
    postedDaysAgo: 22,
    salaryLpa: [12, 18],
  },
  {
    key: "aw-hiremint-fullstack",
    tier: "medium",
    title: "Full-Stack Engineer (React + NestJS)",
    company: "Hiremint",
    about: "Hiremint is interview-scheduling software for recruiting teams.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "NestJS (must)", "TypeScript", "PostgreSQL"],
    preferred: ["Docker"],
    responsibilities: ["Build the recruiting dashboard for hiring teams", "Design NestJS services for interview scheduling"],
    source: "wellfound",
    postedDaysAgo: 7,
    salaryLpa: [24, 34],
    screening: ["What is your notice period?"],
  },
  {
    key: "aw-tripwise-booking",
    tier: "medium",
    title: "Frontend Developer - Travel Booking",
    company: "Tripwise",
    about: "Tripwise is a travel booking site for weekend getaways.",
    locations: ["Gurgaon"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "TypeScript", "Redux", "REST APIs"],
    preferred: ["Next.js"],
    responsibilities: ["Build hotel and flight booking flows", "Improve search result pages"],
    source: "linkedin",
    postedDaysAgo: 12,
    salaryLpa: [18, 26],
    alsoOn: ["indeed"],
  },
  {
    key: "aw-grocerly-lead-frontend",
    tier: "medium",
    title: "Lead Frontend Engineer",
    company: "Grocerly",
    about: "Grocerly delivers groceries in 20 minutes across six cities.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [6, 9],
    required: ["React (must)", "TypeScript (must)", "design systems", "rendering performance"],
    preferred: ["micro-frontends"],
    responsibilities: ["Lead the web team behind our grocery delivery app", "Split the storefront into micro-frontends"],
    source: "greenhouse",
    postedDaysAgo: 14,
    salaryLpa: [40, 55],
    screening: ["How many engineers have you led?"],
  },
  {
    key: "aw-chartwell-dataviz",
    tier: "medium",
    title: "Frontend Engineer - Data Visualisation",
    company: "Chartwell Analytics",
    about: "Chartwell Analytics turns operational data into interactive reports.",
    locations: ["Hyderabad"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "TypeScript", "D3.js", "Canvas API"],
    preferred: ["WebGL"],
    responsibilities: ["Build interactive charts for our analytics dashboard", "Render large datasets on canvas"],
    source: "greenhouse",
    postedDaysAgo: 10,
  },
  {
    key: "aw-pixelmart-frontend",
    tier: "medium",
    title: "Frontend Developer",
    company: "Pixelmart",
    about: "Pixelmart is a marketplace for illustrations and design assets.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [2, 4],
    required: ["JavaScript", "HTML", "CSS", "React"],
    preferred: ["Tailwind CSS", "Figma"],
    responsibilities: ["Build listing pages for our design marketplace", "Turn Figma designs into responsive pages"],
    source: "indeed",
    postedDaysAgo: 27,
    hrEmail: true,
  },
  {
    key: "aw-voxa-react-native",
    tier: "medium",
    title: "React Native Developer",
    company: "Voxa Audio",
    about: "Voxa Audio is a podcast app for Indian languages.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React Native (must)", "React", "TypeScript", "Redux"],
    preferred: ["Kotlin"],
    responsibilities: ["Build the podcast listening app for Android and iOS", "Share code between web and mobile"],
    source: "wellfound",
    postedDaysAgo: 5,
    salaryLpa: [20, 30],
  },
  {
    key: "aw-kitabi-reading-app",
    tier: "medium",
    title: "Senior Frontend Engineer - Reading App",
    company: "Kitabi",
    about: "Kitabi is a reading app with thousands of books in regional languages.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [5, 8],
    required: ["React (must)", "TypeScript", "PWA", "Web Workers"],
    preferred: ["IndexedDB"],
    responsibilities: ["Build our offline-first reading app for students", "Sync highlights across devices"],
    source: "careers",
    postedDaysAgo: 13,
    salaryLpa: [28, 38],
  },
  {
    key: "aw-fleetgrid-tracking",
    tier: "medium",
    title: "Frontend Engineer - Fleet Tracking",
    company: "Fleetgrid",
    about: "Fleetgrid helps truck operators track and plan trips.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["React", "TypeScript", "WebSockets", "Redux"],
    preferred: ["Mapbox"],
    responsibilities: ["Build live fleet maps and trip timelines", "Stream vehicle positions over WebSockets"],
    source: "lever",
    postedDaysAgo: 18,
  },
  {
    key: "aw-scribbledoc-editor",
    tier: "medium",
    title: "Frontend Engineer - Document Editor",
    company: "Scribbledoc",
    about: "Scribbledoc is a shared notes app for student project groups.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["React", "TypeScript", "WebSockets", "state management"],
    preferred: ["CRDTs"],
    responsibilities: ["Build the real-time collaboration features of our document editor", "Handle offline edits and merges"],
    source: "greenhouse",
    postedDaysAgo: 4,
    salaryLpa: [22, 32],
  },
  {
    key: "aw-ticketeer-events",
    tier: "medium",
    title: "Frontend Developer - Event Ticketing",
    company: "Ticketeer",
    about: "Ticketeer sells tickets for concerts and comedy shows.",
    locations: ["Mumbai"],
    workMode: "onsite",
    yoe: [3, 6],
    required: ["React", "JavaScript", "Redux", "REST APIs"],
    preferred: ["Next.js"],
    responsibilities: ["Build seat selection and checkout for live events", "Handle traffic spikes during ticket drops"],
    source: "naukri",
    postedDaysAgo: 8,
    salaryLpa: [15, 24],
  },
  {
    key: "aw-apexdesk-frontend",
    tier: "medium",
    title: "Software Engineer - Frontend",
    company: "Apexdesk",
    about: "Apexdesk is a CRM for B2B sales teams.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [2, 5],
    required: ["React", "TypeScript", "Redux", "GraphQL (must)"],
    preferred: ["Storybook"],
    responsibilities: ["Build the CRM dashboard used by B2B sales teams", "Design GraphQL queries with the backend team"],
    source: "lever",
    postedDaysAgo: 6,
    salaryLpa: [20, 30],
  },
  {
    key: "aw-nivesh-wealth-dashboard",
    tier: "medium",
    title: "Frontend Engineer - Wealth Dashboard",
    company: "Nivesh Wealth",
    about: "Nivesh Wealth provides investment platforms to banks.",
    locations: ["Hyderabad"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "TypeScript", "Redux", "Jest"],
    preferred: ["Highcharts"],
    responsibilities: ["Build the wealth dashboard for our banking partners", "Visualise portfolios and goals"],
    source: "indeed",
    postedDaysAgo: 3,
    salaryLpa: [24, 34],
  },
  {
    key: "aw-growthdesk-mern",
    tier: "medium",
    title: "Full-Stack Developer (MERN)",
    company: "Growthdesk",
    about: "Growthdesk is email marketing software for B2B companies.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["React", "Node.js", "MongoDB", "Express"],
    preferred: ["Docker"],
    responsibilities: ["Build campaign dashboards for B2B marketers", "Own Node.js services for email campaigns"],
    source: "wellfound",
    postedDaysAgo: 24,
  },
  {
    key: "aw-docuflow-senior-fullstack",
    tier: "medium",
    title: "Senior Full-Stack Engineer",
    company: "Docuflow",
    about: "Docuflow automates contract paperwork for legal teams.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [6, 9],
    required: ["TypeScript (must)", "React", "Node.js", "PostgreSQL"],
    preferred: ["AWS", "Docker"],
    responsibilities: ["Build document workflow automation for legal teams", "Own services from API to UI"],
    source: "greenhouse",
    postedDaysAgo: 9,
    salaryLpa: [35, 48],
  },
  {
    key: "aw-carepoint-angular",
    tier: "medium",
    title: "Angular Developer",
    company: "Carepoint",
    about: "Carepoint builds practice-management software for clinics.",
    locations: ["Bengaluru"],
    workMode: "onsite",
    yoe: [3, 6],
    required: ["Angular", "TypeScript", "RxJS", "REST APIs"],
    preferred: ["Jest"],
    responsibilities: ["Build appointment scheduling screens", "Integrate REST APIs for billing"],
    source: "careers",
    postedDaysAgo: 30,
    screening: ["How many years of Angular experience do you have?"],
  },
  {
    key: "aw-quickcart-senior-react",
    tier: "medium",
    title: "Senior React Developer",
    company: "Quickcart",
    about: "Quickcart is a quick-commerce app in the NCR region.",
    locations: ["Noida"],
    workMode: "hybrid",
    yoe: [5, 8],
    required: ["React (must)", "TypeScript", "Redux", "Jest"],
    preferred: ["Next.js"],
    responsibilities: ["Build our quick-commerce web app", "Improve checkout conversion"],
    source: "naukri",
    postedDaysAgo: 2,
    salaryLpa: [25, 35],
    alsoOn: ["linkedin"],
  },
  {
    key: "aw-prepwise-test-prep",
    tier: "medium",
    title: "Frontend Developer - Test Prep",
    company: "Prepwise",
    about: "Prepwise helps students prepare for entrance exams.",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [1, 3],
    required: ["JavaScript", "React", "HTML", "CSS"],
    preferred: ["Firebase"],
    responsibilities: ["Build mock-test experiences for students", "Improve page speed on low-end phones"],
    source: "indeed",
    postedDaysAgo: 15,
    salaryLpa: [8, 14],
  },
  {
    key: "aw-venturely-fullstack",
    tier: "medium",
    title: "Full-Stack Engineer",
    company: "Venturely",
    about: "Venturely builds investor-relations portals for venture funds.",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["TypeScript", "Node.js", "React", "GraphQL"],
    preferred: ["AWS"],
    responsibilities: ["Build the investor relations portal for venture funds", "Design GraphQL APIs"],
    source: "wellfound",
    postedDaysAgo: 1,
    salaryLpa: [26, 36],
    alsoOn: ["linkedin"],
    screening: ["What is your notice period?"],
  },
  {
    key: "aw-kisanlens-frontend",
    tier: "medium",
    title: "Frontend Engineer",
    company: "Kisanlens",
    about: "Kisanlens gives farmers crop-health insights from sensors.",
    locations: ["Chennai"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "TypeScript", "Redux", "REST APIs"],
    preferred: ["Leaflet"],
    responsibilities: ["Build farm monitoring dashboards for agronomists", "Show sensor data on maps"],
    source: "careers",
    postedDaysAgo: 20,
    hrEmail: true,
  },
];

/** Compact builder for the low tier (roles far from the demo candidate's profile). */
function low(
  key: string,
  source: DemoSourceId,
  title: string,
  company: string,
  about: string,
  place: { locations: string[]; workMode: JobWorkMode; yoe: [number, number]; postedDaysAgo: number; salaryLpa?: [number, number] },
  skills: { required: string[]; preferred?: string[] },
  responsibilities: string[],
  extra: Partial<Pick<AutomationJobSpec, "screening" | "hrEmail" | "alsoOn" | "extras">> = {},
): AutomationJobSpec {
  return { key, tier: "low", source, title, company, about, ...place, required: skills.required, preferred: skills.preferred ?? [], responsibilities, ...extra };
}

const LOW: AutomationJobSpec[] = [
  low(
    "aw-kredito-java-backend",
    "naukri",
    "Java Backend Engineer",
    "Kredito",
    "Kredito offers instant credit lines to salaried professionals.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [4, 7], postedDaysAgo: 3, salaryLpa: [20, 32] },
    { required: ["Java (must)", "Spring Boot (must)", "Microservices", "MySQL"], preferred: ["Kafka", "Kubernetes"] },
    ["Build lending microservices", "Own loan disbursal APIs"],
    { alsoOn: ["linkedin"], screening: ["How many years of Spring Boot experience do you have?"] },
  ),
  low(
    "aw-tributary-data-engineer",
    "lever",
    "Data Engineer",
    "Tributary Analytics",
    "Tributary Analytics builds data platforms for retail banks.",
    { locations: ["Pune"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 12, salaryLpa: [18, 30] },
    { required: ["Python (must)", "SQL", "Apache Spark", "Airflow"], preferred: ["Kafka", "AWS"] },
    ["Build batch and streaming data pipelines", "Model data for the analytics team"],
  ),
  low(
    "aw-cloudhaven-devops",
    "careers",
    "DevOps Engineer",
    "Cloudhaven",
    "Cloudhaven runs managed hosting for SaaS start-ups.",
    { locations: ["Hyderabad"], workMode: "onsite", yoe: [3, 6], postedDaysAgo: 21 },
    { required: ["Kubernetes (must)", "Docker", "Terraform", "CI/CD"], preferred: ["AWS", "Prometheus"] },
    ["Run Kubernetes clusters for customer workloads", "Automate infrastructure with Terraform"],
  ),
  low(
    "aw-qualitas-qa-automation",
    "indeed",
    "QA Automation Engineer",
    "Qualitas Labs",
    "Qualitas Labs provides testing services to banks and insurers.",
    { locations: ["Chennai"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 7, salaryLpa: [8, 14] },
    { required: ["Selenium (must)", "Java", "TestNG", "API testing"], preferred: ["Appium"] },
    ["Automate regression suites for banking apps", "Report and track defects"],
  ),
  low(
    "aw-swiftride-android",
    "naukri",
    "Android Developer",
    "Swiftride",
    "Swiftride is a bike-taxi app in tier-2 cities.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 5, salaryLpa: [16, 26] },
    { required: ["Kotlin (must)", "Android SDK", "Jetpack Compose", "Coroutines"], preferred: ["Firebase"] },
    ["Build the rider app for Android", "Improve app start-up time on budget phones"],
    { screening: ["Are you an immediate joiner?"] },
  ),
  low(
    "aw-pulsefit-ios",
    "wellfound",
    "iOS Engineer",
    "Pulsefit",
    "Pulsefit is a fitness-coaching app.",
    { locations: ["Remote - India"], workMode: "remote", yoe: [3, 6], postedDaysAgo: 17 },
    { required: ["Swift (must)", "SwiftUI", "Core Data", "XCTest"], preferred: ["Combine"] },
    ["Build workout tracking features for iPhone", "Integrate HealthKit data"],
  ),
  low(
    "aw-salesbridge-inside-sales",
    "careers",
    "Inside Sales Representative",
    "Salesbridge",
    "Salesbridge sells payroll software to small businesses.",
    { locations: ["Mumbai"], workMode: "onsite", yoe: [1, 3], postedDaysAgo: 2, salaryLpa: [4, 7] },
    { required: ["B2B sales", "CRM tools", "Cold calling"] },
    ["Qualify inbound leads", "Book demos for the account executives"],
    { hrEmail: true },
  ),
  low(
    "aw-vendora-account-executive",
    "linkedin",
    "Enterprise Account Executive",
    "Vendora",
    "Vendora is procurement software for large enterprises.",
    { locations: ["Gurgaon"], workMode: "hybrid", yoe: [5, 8], postedDaysAgo: 26, salaryLpa: [25, 40] },
    { required: ["Enterprise sales", "Salesforce CRM", "Negotiation"] },
    ["Close enterprise deals in North India", "Build pipeline with CXOs"],
  ),
  low(
    "aw-neuronest-ml-engineer",
    "greenhouse",
    "Machine Learning Engineer",
    "Neuronest",
    "Neuronest builds demand-forecasting models for retailers.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 4, salaryLpa: [30, 45] },
    { required: ["Python (must)", "machine learning (must)", "PyTorch", "MLOps"], preferred: ["Kubernetes"] },
    ["Train and ship forecasting models", "Own the model deployment pipeline"],
    { alsoOn: ["linkedin"], screening: ["Which ML frameworks have you used in production?"] },
  ),
  low(
    "aw-finserv-dotnet",
    "indeed",
    ".NET Developer",
    "Finserv Core",
    "Finserv Core builds core-banking software.",
    { locations: ["Hyderabad"], workMode: "onsite", yoe: [3, 6], postedDaysAgo: 33 },
    { required: ["C# (must)", "ASP.NET Core", "SQL Server", "Azure"] },
    ["Build core-banking modules", "Maintain SQL Server stored procedures"],
  ),
  low(
    "aw-rapidpay-golang",
    "lever",
    "Golang Backend Engineer",
    "Rapidpay",
    "Rapidpay processes payments for online merchants.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 6, salaryLpa: [28, 40] },
    { required: ["Go (must)", "gRPC", "PostgreSQL", "Kafka"] },
    ["Build high-throughput payment services", "Own settlement reconciliation jobs"],
  ),
  low(
    "aw-uptimely-sre",
    "greenhouse",
    "Site Reliability Engineer",
    "Uptimely",
    "Uptimely is an uptime monitoring service.",
    { locations: ["Remote - India"], workMode: "remote", yoe: [4, 7], postedDaysAgo: 11 },
    { required: ["Kubernetes (must)", "Linux", "Prometheus", "Terraform"] },
    ["Keep our monitoring platform reliable", "Run incident response and postmortems"],
  ),
  low(
    "aw-pebblemark-product-designer",
    "wellfound",
    "Product Designer",
    "Pebblemark",
    "Pebblemark makes personal-finance apps.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 9 },
    { required: ["Figma (must)", "UX research", "Prototyping", "design systems"] },
    ["Design budgeting flows end to end", "Run usability tests with customers"],
  ),
  low(
    "aw-numeriq-data-analyst",
    "careers",
    "Data Analyst",
    "Numeriq Insights",
    "Numeriq Insights runs market research for consumer brands.",
    { locations: ["Pune"], workMode: "hybrid", yoe: [2, 4], postedDaysAgo: 40, salaryLpa: [8, 12] },
    { required: ["SQL (must)", "Excel", "Tableau", "Python"] },
    ["Build weekly sales reports", "Analyse survey data for clients"],
  ),
  low(
    "aw-cloudstack-salesforce",
    "naukri",
    "Salesforce Developer",
    "Cloudstack Consulting",
    "Cloudstack Consulting implements CRM systems.",
    { locations: ["Noida"], workMode: "onsite", yoe: [3, 6], postedDaysAgo: 14 },
    { required: ["Apex (must)", "Salesforce Lightning", "SOQL"] },
    ["Customise Salesforce for clients", "Build Lightning components"],
  ),
  low(
    "aw-corelink-sap-abap",
    "naukri",
    "SAP ABAP Consultant",
    "Corelink Consulting",
    "Corelink Consulting implements ERP systems for manufacturers.",
    { locations: ["Kolkata"], workMode: "onsite", yoe: [4, 8], postedDaysAgo: 29 },
    { required: ["SAP ABAP (must)", "SAP S/4HANA", "BAPI"] },
    ["Develop ABAP reports and enhancements", "Support S/4HANA migrations"],
  ),
  low(
    "aw-voltiq-embedded",
    "careers",
    "Embedded Software Engineer",
    "Voltiq",
    "Voltiq designs battery-management systems for electric scooters.",
    { locations: ["Pune"], workMode: "onsite", yoe: [3, 6], postedDaysAgo: 8, salaryLpa: [14, 22] },
    { required: ["C++ (must)", "Embedded C", "RTOS", "CAN protocol"] },
    ["Write firmware for battery controllers", "Debug hardware on the bench"],
  ),
  low(
    "aw-brightframe-video-editor",
    "indeed",
    "Video Editor",
    "Brightframe Media",
    "Brightframe Media produces YouTube channels for brands.",
    { locations: ["Mumbai"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 3, salaryLpa: [5, 9] },
    { required: ["Adobe Premiere Pro (must)", "After Effects", "Colour grading"] },
    ["Edit long-form videos and shorts for creator channels", "Design motion graphics and thumbnails"],
  ),
  low(
    "aw-supportly-customer-success",
    "lever",
    "Customer Success Manager",
    "Supportly",
    "Supportly is help-desk software for small teams.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 16 },
    { required: ["Customer onboarding", "Account management", "Renewals"] },
    ["Onboard B2B SaaS customers", "Drive renewals and expansion"],
  ),
  low(
    "aw-peoplefirst-hrbp",
    "linkedin",
    "HR Business Partner",
    "Peoplefirst",
    "Peoplefirst is a staffing company for hospitality businesses.",
    { locations: ["Hyderabad"], workMode: "onsite", yoe: [5, 9], postedDaysAgo: 20 },
    { required: ["Employee relations", "HR policies", "Talent management"] },
    ["Partner with business heads on people plans", "Run performance reviews"],
  ),
  low(
    "aw-quillstack-content-writer",
    "careers",
    "Content Writer - Technology",
    "Quillstack Media",
    "Quillstack Media writes blogs and newsletters for software companies.",
    { locations: ["Remote - India"], workMode: "remote", yoe: [1, 4], postedDaysAgo: 35, salaryLpa: [4, 8] },
    { required: ["Technical writing", "SEO writing", "Editing"] },
    ["Write long-form articles for software clients", "Edit freelance submissions"],
    { hrEmail: true },
  ),
  low(
    "aw-shopnest-django",
    "greenhouse",
    "Python Backend Developer (Django)",
    "Shopnest",
    "Shopnest is inventory software for kirana stores.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 5, salaryLpa: [16, 26] },
    { required: ["Python (must)", "Django (must)", "PostgreSQL", "Celery"], preferred: ["Redis"] },
    ["Build inventory and billing APIs", "Optimise slow database queries"],
    { alsoOn: ["indeed"] },
  ),
  low(
    "aw-rideon-flutter",
    "naukri",
    "Flutter Developer",
    "Rideon",
    "Rideon is a car-rental marketplace.",
    { locations: ["Chennai"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 10 },
    { required: ["Flutter (must)", "Dart", "Firebase", "REST APIs"] },
    ["Build the customer app in Flutter", "Integrate payment and booking APIs"],
  ),
  low(
    "aw-netlink-network-engineer",
    "indeed",
    "Network Engineer",
    "Netlink Infra",
    "Netlink Infra manages office networks for enterprises.",
    { locations: ["Noida"], workMode: "onsite", yoe: [3, 6], postedDaysAgo: 44 },
    { required: ["CCNA", "Routing and switching", "Firewalls"] },
    ["Configure routers and switches at client sites", "Troubleshoot network outages"],
  ),
  low(
    "aw-stratacloud-architect",
    "lever",
    "Cloud Architect (AWS)",
    "Stratacloud",
    "Stratacloud migrates enterprises to the cloud.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [10, 15], postedDaysAgo: 13, salaryLpa: [50, 70] },
    { required: ["AWS (must)", "Terraform", "Kubernetes", "system design"] },
    ["Design cloud landing zones for enterprise customers", "Lead migration programmes"],
  ),
  low(
    "aw-insightful-business-analyst",
    "careers",
    "Business Analyst",
    "Insightful Consulting",
    "Insightful Consulting advises insurers on digital transformation.",
    { locations: ["Mumbai"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 18 },
    { required: ["Requirements gathering", "SQL", "JIRA"] },
    ["Write functional specifications for insurance systems", "Run workshops with business users"],
  ),
  low(
    "aw-bankwise-java-fullstack",
    "naukri",
    "Java Full-Stack Developer (Angular)",
    "Bankwise",
    "Bankwise builds digital banking channels for co-operative banks.",
    { locations: ["Chennai"], workMode: "onsite", yoe: [4, 7], postedDaysAgo: 7, salaryLpa: [12, 20] },
    { required: ["Java (must)", "Spring Boot (must)", "Angular", "MySQL"] },
    ["Build internet banking features in Java and Angular", "Support banking releases"],
  ),
  low(
    "aw-helpdeskly-support-engineer",
    "indeed",
    "Technical Support Engineer",
    "Helpdeskly",
    "Helpdeskly provides IT support to hospitals and schools.",
    { locations: ["Kochi"], workMode: "onsite", yoe: [1, 3], postedDaysAgo: 23 },
    { required: ["Linux", "Networking", "Ticketing systems"] },
    ["Resolve L1 and L2 support tickets", "Maintain client servers"],
  ),
  low(
    "aw-agilify-scrum-master",
    "careers",
    "Scrum Master",
    "Agilify",
    "Agilify coaches software teams on delivery practices.",
    { locations: ["Pune"], workMode: "hybrid", yoe: [5, 8], postedDaysAgo: 31 },
    { required: ["Agile (must)", "JIRA", "Stakeholder management"] },
    ["Facilitate ceremonies for three teams", "Remove delivery blockers"],
  ),
  low(
    "aw-predictiv-data-scientist",
    "greenhouse",
    "Data Scientist",
    "Predictiv",
    "Predictiv predicts customer churn for telecom operators.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 15, salaryLpa: [25, 38] },
    { required: ["Python (must)", "machine learning (must)", "Statistics", "SQL"] },
    ["Build churn models", "Present insights to operators"],
  ),
  low(
    "aw-shieldline-soc-analyst",
    "linkedin",
    "Security Analyst (SOC)",
    "Shieldline",
    "Shieldline runs a 24x7 security operations centre.",
    { locations: ["Hyderabad"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 6 },
    { required: ["SIEM (must)", "Incident response", "Threat hunting"] },
    ["Monitor alerts in rotating shifts", "Investigate security incidents"],
  ),
  low(
    "aw-oxbow-rust-engineer",
    "wellfound",
    "Rust Systems Engineer",
    "Oxbow Systems",
    "Oxbow Systems builds a time-series database.",
    { locations: ["Remote - India"], workMode: "remote", yoe: [4, 7], postedDaysAgo: 19, salaryLpa: [35, 50] },
    { required: ["Rust (must)", "Linux", "distributed systems"] },
    ["Build the storage engine", "Profile and optimise query execution"],
  ),
  low(
    "aw-pixelplay-unity",
    "careers",
    "Game Developer (Unity)",
    "Pixelplay Games",
    "Pixelplay Games makes casual mobile games.",
    { locations: ["Bengaluru"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 12 },
    { required: ["Unity (must)", "C# (must)", "Game physics"] },
    ["Build gameplay features for casual games", "Optimise games for low-end phones"],
  ),
  low(
    "aw-chainmint-blockchain",
    "wellfound",
    "Blockchain Developer",
    "Chainmint",
    "Chainmint builds tools for on-chain loyalty programmes.",
    { locations: ["Remote - India"], workMode: "remote", yoe: [2, 5], postedDaysAgo: 38 },
    { required: ["Solidity (must)", "Ethereum", "Hardhat"] },
    ["Write and audit smart contracts", "Build indexing services"],
  ),
  low(
    "aw-datakeep-oracle-dba",
    "naukri",
    "Oracle DBA",
    "Datakeep Systems",
    "Datakeep Systems manages databases for large enterprises.",
    { locations: ["Chennai"], workMode: "onsite", yoe: [5, 9], postedDaysAgo: 27 },
    { required: ["Oracle Database (must)", "PL/SQL", "RMAN"] },
    ["Administer production Oracle databases", "Plan backups and recovery"],
  ),
  low(
    "aw-clusterly-platform-engineer",
    "lever",
    "Kubernetes Platform Engineer",
    "Clusterly",
    "Clusterly offers managed Kubernetes for start-ups.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [4, 7], postedDaysAgo: 4 },
    { required: ["Kubernetes (must)", "Go", "Helm", "Terraform"] },
    ["Build our internal developer platform", "Automate cluster upgrades"],
  ),
  low(
    "aw-legacyworks-cobol",
    "naukri",
    "Mainframe Developer (COBOL)",
    "Legacyworks",
    "Legacyworks maintains mainframe systems for insurers.",
    { locations: ["Pune"], workMode: "onsite", yoe: [5, 10], postedDaysAgo: 42 },
    { required: ["COBOL (must)", "JCL", "DB2"] },
    ["Maintain batch jobs", "Support policy administration systems"],
  ),
  low(
    "aw-adsprout-performance-marketing",
    "linkedin",
    "Marketing Manager - Performance",
    "Adsprout",
    "Adsprout is a performance-marketing agency for D2C brands.",
    { locations: ["Mumbai"], workMode: "hybrid", yoe: [4, 7], postedDaysAgo: 9 },
    { required: ["Google Ads", "Meta Ads", "SEO"] },
    ["Run paid campaigns for D2C brands", "Report on campaign ROI"],
  ),
  low(
    "aw-pixelnest-uiux",
    "careers",
    "UI/UX Designer",
    "Pixelnest Studio",
    "Pixelnest Studio designs apps for start-ups.",
    { locations: ["Bengaluru"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 25 },
    { required: ["Figma (must)", "User research", "Wireframing"] },
    ["Design mobile apps for start-up clients", "Build clickable prototypes"],
  ),
  low(
    "aw-talentloop-recruiter",
    "indeed",
    "Talent Acquisition Specialist",
    "Talentloop",
    "Talentloop hires engineers for product companies.",
    { locations: ["Gurgaon"], workMode: "hybrid", yoe: [2, 5], postedDaysAgo: 5 },
    { required: ["Technical recruiting", "Sourcing", "Stakeholder management"] },
    ["Hire engineers for client companies", "Manage candidate pipelines"],
  ),
  low(
    "aw-siliconvale-hardware",
    "careers",
    "Hardware Design Engineer",
    "Siliconvale",
    "Siliconvale designs chips for smart meters.",
    { locations: ["Hyderabad"], workMode: "onsite", yoe: [3, 7], postedDaysAgo: 34 },
    { required: ["Verilog (must)", "FPGA", "PCB design"] },
    ["Design and verify FPGA logic", "Review PCB layouts"],
  ),
  low(
    "aw-warehousely-etl",
    "naukri",
    "ETL Developer (Informatica)",
    "Warehousely",
    "Warehousely builds data warehouses for retailers.",
    { locations: ["Chennai"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 16 },
    { required: ["Informatica (must)", "SQL", "Data warehousing"] },
    ["Build ETL jobs for retail data", "Tune slow warehouse loads"],
  ),
  low(
    "aw-mobitest-appium",
    "indeed",
    "Automation Test Engineer (Appium)",
    "Mobitest",
    "Mobitest tests mobile apps for banks.",
    { locations: ["Noida"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 8 },
    { required: ["Appium (must)", "Java", "Selenium", "Mobile testing"] },
    ["Automate mobile regression tests", "Maintain the device lab"],
  ),
  low(
    "aw-webcart-php",
    "naukri",
    "PHP Developer (Laravel)",
    "Webcart Solutions",
    "Webcart Solutions builds online shops for small retailers.",
    { locations: ["Ahmedabad"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 21, salaryLpa: [5, 9] },
    { required: ["PHP (must)", "Laravel (must)", "MySQL", "jQuery"] },
    ["Build e-commerce sites in Laravel", "Maintain client websites"],
  ),
  low(
    "aw-docsmith-technical-writer",
    "wellfound",
    "Technical Writer",
    "Docsmith",
    "Docsmith writes API documentation for developer-tool companies.",
    { locations: ["Remote - India"], workMode: "remote", yoe: [2, 5], postedDaysAgo: 11 },
    { required: ["API documentation", "Markdown", "Docs-as-code"] },
    ["Write API reference and guides", "Review SDK samples"],
  ),
  low(
    "aw-movewell-operations",
    "linkedin",
    "Operations Manager - Logistics",
    "Movewell",
    "Movewell runs same-day delivery for pharmacies.",
    { locations: ["Delhi"], workMode: "onsite", yoe: [5, 8], postedDaysAgo: 30 },
    { required: ["Fleet operations", "Vendor management", "Excel"] },
    ["Run last-mile delivery operations", "Manage delivery partners"],
  ),
  low(
    "aw-buildright-site-engineer",
    "indeed",
    "Site Engineer (Civil)",
    "Buildright Infra",
    "Buildright Infra builds residential projects.",
    { locations: ["Pune"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 3 },
    { required: ["AutoCAD", "Site supervision", "Quantity surveying"] },
    ["Supervise construction sites", "Track material usage"],
  ),
  low(
    "aw-capitalwise-financial-analyst",
    "careers",
    "Financial Analyst",
    "Capitalwise",
    "Capitalwise advises mid-size companies on fundraising.",
    { locations: ["Mumbai"], workMode: "hybrid", yoe: [2, 5], postedDaysAgo: 45 },
    { required: ["Financial modelling", "Excel", "Valuation"] },
    ["Build financial models for clients", "Prepare investor memos"],
  ),
  low(
    "aw-hivemind-hadoop",
    "lever",
    "Big Data Engineer (Hadoop)",
    "Hivemind Data",
    "Hivemind Data processes clickstream data for publishers.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [4, 7], postedDaysAgo: 28 },
    { required: ["Hadoop (must)", "Apache Spark", "Hive", "Scala"] },
    ["Build clickstream processing jobs", "Maintain the Hadoop cluster"],
  ),
  low(
    "aw-quantedge-cpp-trading",
    "greenhouse",
    "C++ Developer - Trading Systems",
    "Quantedge",
    "Quantedge is a proprietary trading firm.",
    { locations: ["Mumbai"], workMode: "onsite", yoe: [3, 7], postedDaysAgo: 2, salaryLpa: [40, 70] },
    { required: ["C++ (must)", "Low-latency systems", "Linux", "Multithreading"] },
    ["Build low-latency trading systems", "Optimise order routing"],
    { screening: ["Are you open to working from our Mumbai office five days a week?"] },
  ),
  low(
    "aw-reportly-power-bi",
    "naukri",
    "Power BI Developer",
    "Reportly",
    "Reportly builds management dashboards for manufacturers.",
    { locations: ["Hyderabad"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 19 },
    { required: ["Power BI (must)", "DAX", "SQL"] },
    ["Build Power BI reports for plant managers", "Model data from ERP systems"],
  ),
  low(
    "aw-serverline-linux-admin",
    "indeed",
    "Linux System Administrator",
    "Serverline",
    "Serverline hosts servers for regional businesses.",
    { locations: ["Noida"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 37 },
    { required: ["Linux (must)", "Bash scripting", "Ansible"] },
    ["Maintain Linux servers", "Automate patching with Ansible"],
  ),
  low(
    "aw-promptly-llm-research",
    "greenhouse",
    "AI Research Engineer (LLMs)",
    "Promptly AI",
    "Promptly AI builds language models for Indian languages.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 1, salaryLpa: [40, 60] },
    { required: ["Python (must)", "LLMs (must)", "PyTorch", "Model evaluation"] },
    ["Fine-tune language models", "Build evaluation suites"],
  ),
  low(
    "aw-callnest-support-executive",
    "naukri",
    "Customer Support Executive",
    "Callnest",
    "Callnest runs customer support for e-commerce brands.",
    { locations: ["Kolkata"], workMode: "onsite", yoe: [0, 2], postedDaysAgo: 4, salaryLpa: [3, 4] },
    { required: ["Customer support", "English communication", "Ticketing systems"] },
    ["Answer customer calls and chats", "Resolve order issues"],
  ),
  low(
    "aw-nowline-servicenow",
    "careers",
    "ServiceNow Developer",
    "Nowline",
    "Nowline implements IT service management for enterprises.",
    { locations: ["Hyderabad"], workMode: "hybrid", yoe: [3, 6], postedDaysAgo: 24 },
    { required: ["ServiceNow (must)", "JavaScript", "ITSM"] },
    ["Build ServiceNow workflows for IT teams", "Integrate ServiceNow with other systems"],
  ),
  low(
    "aw-skyforge-presales",
    "linkedin",
    "Solutions Architect - Pre-sales",
    "Skyforge Cloud",
    "Skyforge Cloud resells cloud services to enterprises.",
    { locations: ["Bengaluru"], workMode: "hybrid", yoe: [8, 12], postedDaysAgo: 10 },
    { required: ["Pre-sales", "AWS", "Solution design"] },
    ["Design cloud solutions for enterprise deals", "Run customer workshops"],
  ),
  low(
    "aw-ledgerbay-accounts",
    "naukri",
    "Accounts Executive",
    "Ledgerbay",
    "Ledgerbay provides bookkeeping to small businesses.",
    { locations: ["Chennai"], workMode: "onsite", yoe: [1, 3], postedDaysAgo: 13, salaryLpa: [3, 5] },
    { required: ["Tally ERP (must)", "GST filing", "Accounting"] },
    ["Maintain client books in Tally", "File GST returns"],
  ),
  low(
    "aw-botwise-robotics",
    "careers",
    "Robotics Engineer",
    "Botwise",
    "Botwise builds warehouse robots.",
    { locations: ["Pune"], workMode: "onsite", yoe: [2, 5], postedDaysAgo: 17 },
    { required: ["ROS (must)", "C++", "Python", "Computer vision"] },
    ["Program warehouse robots", "Integrate vision sensors"],
  ),
];

const CATALOGUE: AutomationJobSpec[] = [...HIGH, ...MEDIUM, ...LOW];

// ---------------------------------------------------------------- builders

const DAY_MS = 86_400_000;
const FIRST_JOB_ID = 7101;

/** "Reelcraft Studio" -> "reelcraft-studio" (used for .example / .test hosts). */
export function demoCompanySlug(company: string): string {
  return company
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function scenarioOf(spec: AutomationJobSpec): DemoScenario {
  return spec.scenario ?? (MANUAL_SOURCES.has(spec.source) ? "manual_only" : "auto_success");
}

function channelOf(spec: AutomationJobSpec): DemoChannel {
  return spec.channel ?? "api";
}

const skillName = (s: string) => s.replace(/\s*\((?:must|mandatory|required)\)\s*$/i, "").trim();
const isMandatory = (s: string) => /\((?:must|mandatory|required)\)\s*$/i.test(s);

function applyUrlOf(spec: AutomationJobSpec, id: number, appUrl: string): string {
  if (channelOf(spec) === "browser") return `${appUrl.replace(/\/+$/, "")}/demo/ats/greenhouse/${spec.key}`;
  return `https://careers.${demoCompanySlug(spec.company)}.example/jobs/${id}`;
}

function hrEmailOf(spec: AutomationJobSpec): string | undefined {
  return spec.hrEmail ? `hiring@${demoCompanySlug(spec.company)}.test` : undefined;
}

function description(spec: AutomationJobSpec, applyUrl: string, hrEmail: string | undefined): string {
  const [min, max] = spec.yoe;
  const lines: string[] = [
    DEMO_NOTICE,
    "",
    `${spec.title} at ${spec.company}`,
    "",
    "About us",
    spec.about,
    "",
    "What you'll do",
    ...spec.responsibilities.map((r) => `- ${r}`),
    "",
    "Requirements",
    `- ${min}-${max} years of professional experience`,
    ...spec.required.map((s) => (isMandatory(s) ? `- Must have strong hands-on experience with ${skillName(s)}` : `- Experience with ${skillName(s)}`)),
    ...(spec.extras ?? []).map((e) => `- ${e}`),
  ];
  if (spec.preferred.length > 0) lines.push("", "Nice to have", ...spec.preferred.map((s) => `- ${s}`));
  lines.push("", `Location: ${spec.locations.join(", ")} (${spec.workMode})`);
  if (spec.salaryLpa) lines.push(`Compensation: ${spec.salaryLpa[0]}-${spec.salaryLpa[1]} LPA`);
  if (spec.screening?.length) lines.push("", "Screening questions", ...spec.screening.map((q) => `- ${q}`));
  lines.push("", "How to apply");
  lines.push(hrEmail ? `Email your resume to ${hrEmail} with the subject "${spec.title} - <your name>".` : `Apply on the official page: ${applyUrl}`);
  return lines.join("\n");
}

function toRaw(spec: AutomationJobSpec, index: number, sourceId: DemoSourceId, appUrl: string, now: Date): RawImportedJob {
  const source = DEMO_SOURCES[sourceId];
  const id = FIRST_JOB_ID + index;
  const slug = demoCompanySlug(spec.company);
  const applyUrl = applyUrlOf(spec, id, appUrl);
  const hrEmail = hrEmailOf(spec);
  // Hours offset keeps postings from the same day apart; still a pure function of `now`.
  const posted = new Date(now.getTime() - spec.postedDaysAgo * DAY_MS - (index % 9) * 3_600_000);
  const expires = new Date(posted.getTime() + 60 * DAY_MS);
  const scenario = scenarioOf(spec);
  const channel = channelOf(spec);
  return {
    provider: source.platform,
    importMethod: "SEEDED_DEMO",
    externalId: `demo:${sourceId}:${id}`,
    sourceUrl: sourceId === "careers" && channel === "api" ? applyUrl : source.listingUrl({ key: spec.key, id, slug }),
    attribution: source.label,
    raw: { kind: "demo_provider", demo: true, demoScenario: scenario, demoChannel: channel, demoSource: sourceId, key: spec.key },
    text: description(spec, applyUrl, hrEmail),
    descriptionLevel: "FULL",
    hints: {
      platform: source.platform,
      title: spec.title,
      company: spec.company,
      companyWebsite: `https://${slug}.example`,
      location: spec.locations,
      workMode: spec.workMode,
      employmentType: "full_time",
      requiredSkillNames: spec.required.map((s) => (isMandatory(s) ? `${skillName(s)} (must)` : s)),
      preferredSkillNames: spec.preferred,
      experienceMinYears: spec.yoe[0],
      experienceMaxYears: spec.yoe[1],
      salaryMin: spec.salaryLpa ? spec.salaryLpa[0] * 100_000 : undefined,
      salaryMax: spec.salaryLpa ? spec.salaryLpa[1] * 100_000 : undefined,
      currency: spec.salaryLpa ? "INR" : undefined,
      postedAt: posted.toISOString(),
      expiresAt: expires.toISOString(),
      applyUrl,
      hrEmail,
      applyMethod: hrEmail ? "EMAIL" : undefined,
      applicationInstructions: hrEmail ? `Email your resume to ${hrEmail} with the subject "${spec.title} - <your name>".` : undefined,
      responsibilities: spec.responsibilities,
      isDemo: true,
    },
  };
}

/** Number of distinct jobs in the catalogue (the most `count` can return). */
export const DEMO_AUTOMATION_JOB_COUNT = CATALOGUE.length;

/**
 * 100+ deterministic demo jobs across simulated providers, followed by cross-provider duplicates (the same
 * title + company + primary city from another simulated source, so the import merges them into one job).
 */
export function generateDemoAutomationJobs(opts: DemoJobsOptions): RawImportedJob[] {
  const now = opts.now ?? new Date();
  const count = Math.max(0, Math.min(opts.count ?? 110, CATALOGUE.length));
  const specs = CATALOGUE.slice(0, count);
  const jobs = specs.map((spec, i) => toRaw(spec, i, spec.source, opts.appUrl, now));
  specs.forEach((spec, i) => {
    for (const other of spec.alsoOn ?? []) if (other !== spec.source) jobs.push(toRaw(spec, i, other, opts.appUrl, now));
  });
  return jobs;
}

/** The job's tier in the catalogue (tests and the score-distribution script compare it with the real score). */
export function demoAutomationJobTier(key: string): DemoTier | null {
  return CATALOGUE.find((s) => s.key === key)?.tier ?? null;
}

// ---------------------------------------------------------------- demo ATS page

export const DEMO_NOTICE_PERIOD_QUESTION = "What is your notice period?";
export const DEMO_WORK_AUTH_QUESTION = "Are you authorised to work in India?";
export const DEMO_SINGAPORE_PERMIT_QUESTION = "Do you hold a valid work permit for Singapore?";

export interface DemoAtsJob {
  title: string;
  company: string;
  locations: string[];
  /** Extra questions on the page (the standard fields - name, email, notice period, resume - are always there). */
  screening: string[];
  variant: "standard" | "captcha" | "login";
  applyUrl: string;
}

/** A demo job for the local demo ATS page (/demo/ats/<platform>/<slug>), or null. */
export function demoAutomationJobBySlug(slug: string, opts: { appUrl: string }): DemoAtsJob | null {
  const index = CATALOGUE.findIndex((s) => s.key === slug);
  const spec = CATALOGUE[index];
  if (!spec) return null;
  const scenario = scenarioOf(spec);
  const screening = [DEMO_WORK_AUTH_QUESTION, ...(scenario === "unknown_question" ? [DEMO_SINGAPORE_PERMIT_QUESTION] : []), ...(spec.screening ?? [])];
  return {
    title: spec.title,
    company: spec.company,
    locations: [...spec.locations],
    screening: [...new Set(screening.filter((q) => q !== DEMO_NOTICE_PERIOD_QUESTION))],
    variant: scenario === "captcha" ? "captcha" : scenario === "login_required" || scenario === "mfa" ? "login" : "standard",
    applyUrl: applyUrlOf(spec, FIRST_JOB_ID + index, opts.appUrl),
  };
}
