import type { JobPlatform, JobWorkMode } from "@applywise/types";

/**
 * DEMO CONTENT. Every company, job, URL and email address below is fictional and exists
 * only for local development and tests. Email addresses use the reserved .test TLD and
 * job-board URLs use the reserved .example TLD. Career-page demo jobs point at the local
 * mock ATS pages served by the web app under /demo/ats/*.
 */

export interface DemoJobSpec {
  key: string;
  platform: JobPlatform;
  sourceLabel: string;
  title: string;
  company: string;
  locations: string[];
  workMode: JobWorkMode;
  yoe: [number, number];
  required: string[];
  mandatory?: string[];
  preferred: string[];
  about: string;
  responsibilities: string[];
  extras?: string[];
  screening?: string[];
  apply: { url?: string; email?: string; instructions?: string };
  postedDaysAgo: number;
  salaryLpa?: [number, number];
}

const LOCAL = "{{APP_URL}}";

export const DEMO_JOBS: DemoJobSpec[] = [
  {
    key: "framecraft-senior-frontend",
    platform: "GREENHOUSE",
    sourceLabel: "Greenhouse-like career page (demo)",
    title: "Senior Frontend Engineer - Video Editor",
    company: "Framecraft Labs",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [4, 7],
    required: ["React", "TypeScript", "Canvas API", "State management"],
    mandatory: ["React", "TypeScript"],
    preferred: ["WebGL", "Video editing timelines", "Web Workers", "WebCodecs"],
    about: "Framecraft Labs builds a browser-based video editor for creators. You will own our multi-track timeline and preview canvas.",
    responsibilities: [
      "Build the multi-track video timeline with frame-accurate trimming and drag-and-drop",
      "Optimise canvas rendering performance for long projects",
      "Design state management for undo/redo across complex UI workflows",
    ],
    screening: ["How many years of professional React experience do you have?", "Have you built a timeline or canvas-based editor before?"],
    apply: { url: `${LOCAL}/demo/ats/greenhouse/framecraft-senior-frontend` },
    postedDaysAgo: 2,
    salaryLpa: [32, 45],
  },
  {
    key: "clipstack-react-dev",
    platform: "NAUKRI",
    sourceLabel: "Naukri-like job board (demo)",
    title: "React Developer",
    company: "ClipStack Media",
    locations: ["Bengaluru", "Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["React", "JavaScript", "TypeScript", "REST API"],
    preferred: ["Chunked uploads", "Amazon S3", "Media workflows"],
    about: "ClipStack Media helps agencies manage and review video assets. Our upload pipeline handles multi-GB files.",
    responsibilities: ["Build resumable chunked upload UI for large media files", "Integrate REST APIs for asset review workflows", "Write unit tests with Jest"],
    extras: ["Immediate joiners preferred. Notice period of 30 days or less.", "Please mention your current CTC and expected CTC."],
    apply: { url: "https://demo-naukri.example/job-listings/clipstack-react-developer-3-6-years-1001" },
    postedDaysAgo: 1,
    salaryLpa: [18, 28],
  },
  {
    key: "reelio-fullstack",
    platform: "INSTAHYRE",
    sourceLabel: "Instahyre-like job board (demo)",
    title: "Full-Stack Developer (Node.js + React)",
    company: "Reelio",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "Node.js", "TypeScript", "PostgreSQL"],
    mandatory: ["Node.js"],
    preferred: ["Redis", "Docker", "AWS"],
    about: "Reelio is a short-form video platform for regional creators in India.",
    responsibilities: ["Own features across React frontend and Node.js services", "Design PostgreSQL schemas and REST endpoints", "Improve rendering performance of the creator dashboard"],
    apply: { url: "https://demo-instahyre.example/job-2002-full-stack-developer-at-reelio" },
    postedDaysAgo: 4,
  },
  {
    key: "flowdesk-frontend",
    platform: "LEVER",
    sourceLabel: "Lever-like career page (demo)",
    title: "Frontend Engineer, Workflow Builder",
    company: "Flowdesk",
    locations: ["Pune"],
    workMode: "hybrid",
    yoe: [2, 5],
    required: ["React", "TypeScript", "Complex UI workflows", "State management"],
    preferred: ["XState", "Design systems", "Playwright"],
    about: "Flowdesk is a B2B SaaS workflow automation platform used by operations teams.",
    responsibilities: ["Build a drag-and-drop workflow builder", "Maintain our design system components", "Write end-to-end tests with Playwright"],
    apply: { url: `${LOCAL}/demo/ats/lever/flowdesk-frontend` },
    postedDaysAgo: 6,
    salaryLpa: [20, 30],
  },
  {
    key: "paynest-senior-react",
    platform: "INDEED",
    sourceLabel: "Indeed-like job board (demo)",
    title: "Senior React Engineer",
    company: "PayNest",
    locations: ["Mumbai"],
    workMode: "onsite",
    yoe: [5, 8],
    required: ["React", "TypeScript", "Redux", "Unit testing"],
    mandatory: ["React"],
    preferred: ["Micro-frontends", "Web accessibility"],
    about: "PayNest builds UPI and payments products for small businesses.",
    responsibilities: ["Lead frontend architecture for the merchant dashboard", "Mentor engineers and review code", "Improve accessibility to WCAG AA"],
    extras: ["Work from office 5 days a week in Mumbai."],
    apply: { url: "https://demo-indeed.example/viewjob?jk=paynest-senior-react-3003" },
    postedDaysAgo: 3,
  },
  {
    key: "storyboard-canvas",
    platform: "ASHBY",
    sourceLabel: "Ashby-like career page (demo)",
    title: "Frontend Engineer - Canvas & Graphics",
    company: "Storyboard AI",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 7],
    required: ["TypeScript", "Canvas API", "Rendering performance"],
    mandatory: ["Canvas API"],
    preferred: ["WebGL", "React", "Web Workers"],
    about: "Storyboard AI is a creator tool for turning scripts into animated storyboards.",
    responsibilities: ["Build a high-performance 2D canvas scene editor", "Profile and optimise rendering performance", "Collaborate with ML engineers on generation features"],
    apply: { url: `${LOCAL}/demo/ats/ashby/storyboard-canvas` },
    postedDaysAgo: 5,
    salaryLpa: [28, 40],
  },
  {
    key: "kavach-hr-email-frontend",
    platform: "OTHER",
    sourceLabel: "Email-only HR application (demo)",
    title: "Frontend Developer (React)",
    company: "Kavach Studio",
    locations: ["Bengaluru"],
    workMode: "onsite",
    yoe: [2, 5],
    required: ["React", "JavaScript", "CSS"],
    preferred: ["TypeScript", "Figma"],
    about: "Kavach Studio is a small design-led product studio building apps for D2C brands.",
    responsibilities: ["Convert Figma designs into responsive React components", "Work closely with designers and clients"],
    apply: { email: "hiring@kavach-studio.test", instructions: "Email your resume to hiring@kavach-studio.test with the subject 'Frontend Developer - <Your Name>'." },
    postedDaysAgo: 2,
  },
  {
    key: "mediamint-workday",
    platform: "WORKDAY",
    sourceLabel: "Workday-like career page (demo)",
    title: "Software Engineer II - Media Platform UI",
    company: "MediaMint Global",
    locations: ["Hyderabad"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "TypeScript", "Media workflows"],
    preferred: ["Video editing timelines", "GraphQL", "Webpack"],
    about: "MediaMint Global runs broadcast-grade media operations for OTT networks.",
    responsibilities: ["Build UI for media ingest and QC workflows", "Collaborate with backend teams on GraphQL APIs"],
    extras: ["Bachelor's degree in Computer Science or equivalent experience."],
    apply: { url: `${LOCAL}/demo/ats/workday/mediamint-workday` },
    postedDaysAgo: 9,
  },
  {
    key: "tallyho-junior-frontend",
    platform: "NAUKRI",
    sourceLabel: "Naukri-like job board (demo)",
    title: "Junior Frontend Developer",
    company: "TallyHo Commerce",
    locations: ["Chennai"],
    workMode: "onsite",
    yoe: [1, 2],
    required: ["JavaScript", "HTML", "CSS", "React"],
    preferred: ["Tailwind CSS"],
    about: "TallyHo Commerce is an e-commerce enablement platform for retailers.",
    responsibilities: ["Build storefront pages", "Fix UI bugs across browsers"],
    apply: { url: "https://demo-naukri.example/job-listings/tallyho-junior-frontend-1-2-years-1004" },
    postedDaysAgo: 12,
  },
  {
    key: "orbit-staff-frontend",
    platform: "GREENHOUSE",
    sourceLabel: "Greenhouse-like career page (demo)",
    title: "Staff Frontend Engineer",
    company: "Orbit Analytics",
    locations: ["Gurgaon"],
    workMode: "hybrid",
    yoe: [8, 12],
    required: ["React", "TypeScript", "System design", "Micro-frontends"],
    mandatory: ["System design"],
    preferred: ["GraphQL", "Web Workers"],
    about: "Orbit Analytics provides a SaaS BI dashboard for enterprises.",
    responsibilities: ["Set technical direction for 4 frontend teams", "Own performance budgets and platform tooling"],
    apply: { url: `${LOCAL}/demo/ats/greenhouse/orbit-staff-frontend` },
    postedDaysAgo: 7,
    salaryLpa: [60, 80],
  },
  {
    key: "vidyut-edtech-fullstack",
    platform: "INDEED",
    sourceLabel: "Indeed-like job board (demo)",
    title: "Full Stack Engineer",
    company: "Vidyut Learning",
    locations: ["Hyderabad", "Remote - India"],
    workMode: "remote",
    yoe: [2, 5],
    required: ["React", "Node.js", "MongoDB", "REST API"],
    preferred: ["Next.js", "AWS", "WebSockets"],
    about: "Vidyut Learning is an edtech platform with live classes for students in tier-2 cities.",
    responsibilities: ["Build live-class features with video streaming", "Own Node.js APIs and MongoDB models"],
    apply: { url: "https://demo-indeed.example/viewjob?jk=vidyut-full-stack-3005" },
    postedDaysAgo: 10,
  },
  {
    key: "snapcut-mobile",
    platform: "INSTAHYRE",
    sourceLabel: "Instahyre-like job board (demo)",
    title: "React Native Developer",
    company: "SnapCut",
    locations: ["Bengaluru"],
    workMode: "onsite",
    yoe: [2, 5],
    required: ["React Native", "TypeScript", "Redux"],
    mandatory: ["React Native"],
    preferred: ["Media workflows", "Flutter"],
    about: "SnapCut is a mobile-first video editing app.",
    responsibilities: ["Build mobile editing features", "Integrate native media modules"],
    apply: { url: "https://demo-instahyre.example/job-2006-react-native-developer-at-snapcut" },
    postedDaysAgo: 8,
  },
  {
    key: "ledgerly-backend",
    platform: "LEVER",
    sourceLabel: "Lever-like career page (demo)",
    title: "Backend Engineer (Go)",
    company: "Ledgerly",
    locations: ["Pune"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["Go", "PostgreSQL", "Kafka", "Microservices"],
    mandatory: ["Go"],
    preferred: ["Kubernetes", "AWS"],
    about: "Ledgerly is a fintech accounting platform for SMEs.",
    responsibilities: ["Build ledger microservices in Go", "Operate Kafka event pipelines"],
    apply: { url: `${LOCAL}/demo/ats/lever/ledgerly-backend` },
    postedDaysAgo: 15,
  },
  {
    key: "pixelpress-ui",
    platform: "OTHER",
    sourceLabel: "Email-only HR application (demo)",
    title: "UI Engineer - Design Systems",
    company: "PixelPress",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 6],
    required: ["React", "TypeScript", "Design systems", "CSS"],
    preferred: ["Web accessibility", "Storybook"],
    about: "PixelPress is a SaaS publishing tool for digital magazines.",
    responsibilities: ["Own our React component library", "Drive accessibility across products"],
    apply: { email: "careers@pixelpress.test", instructions: "Send your CV and a short note to careers@pixelpress.test." },
    postedDaysAgo: 3,
  },
  {
    key: "streamyard-in-webrtc",
    platform: "ASHBY",
    sourceLabel: "Ashby-like career page (demo)",
    title: "Senior Software Engineer - Real-time Video",
    company: "LiveLoop",
    locations: ["Remote - Global"],
    workMode: "remote",
    yoe: [5, 9],
    required: ["TypeScript", "WebCodecs", "React", "Media workflows"],
    mandatory: ["WebCodecs"],
    preferred: ["WebGL", "Rust"],
    about: "LiveLoop builds browser-based live streaming studios for creators.",
    responsibilities: ["Build WebRTC-based studio features", "Optimise media pipelines in the browser"],
    extras: ["You must be authorized to work in your country of residence."],
    apply: { url: `${LOCAL}/demo/ats/ashby/streamyard-in-webrtc` },
    postedDaysAgo: 4,
  },
  {
    key: "cartwheel-frontend-lead",
    platform: "NAUKRI",
    sourceLabel: "Naukri-like job board (demo)",
    title: "Frontend Lead",
    company: "Cartwheel Retail",
    locations: ["Gurgaon"],
    workMode: "onsite",
    yoe: [7, 10],
    required: ["React", "Next.js", "TypeScript", "System design"],
    preferred: ["Micro-frontends", "CI/CD"],
    about: "Cartwheel Retail is an omnichannel e-commerce company.",
    responsibilities: ["Lead a team of 6 frontend engineers", "Own Next.js storefront performance"],
    extras: ["Immediate joiner required."],
    apply: { url: "https://demo-naukri.example/job-listings/cartwheel-frontend-lead-7-10-years-1007" },
    postedDaysAgo: 20,
  },
  {
    key: "nimbus-nextjs",
    platform: "INDEED",
    sourceLabel: "Indeed-like job board (demo)",
    title: "Next.js Developer",
    company: "Nimbus Cloudworks",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [2, 4],
    required: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
    preferred: ["Prisma", "PostgreSQL", "Vercel"],
    about: "Nimbus Cloudworks is a developer tools SaaS for infrastructure teams.",
    responsibilities: ["Build dashboard features with Next.js App Router", "Collaborate on API design"],
    apply: { url: "https://demo-indeed.example/viewjob?jk=nimbus-nextjs-3008" },
    postedDaysAgo: 2,
  },
  {
    key: "sutra-video-platform",
    platform: "COMPANY_CAREER_PAGE",
    sourceLabel: "Company career page (demo)",
    title: "Frontend Engineer - Video Collaboration",
    company: "Sutra Video",
    locations: ["Bengaluru", "Remote - India"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "TypeScript", "Video editing timelines", "Chunked uploads"],
    preferred: ["Canvas API", "Amazon S3", "WebSockets"],
    about: "Sutra Video is a video review and approval tool for production houses.",
    responsibilities: ["Build frame-accurate commenting on a video timeline", "Improve large file upload reliability with chunked, resumable uploads"],
    screening: ["Describe a complex UI you built and the state management approach you used."],
    apply: { url: `${LOCAL}/demo/ats/career/sutra-video-platform` },
    postedDaysAgo: 1,
    salaryLpa: [25, 38],
  },
  {
    key: "quantleaf-data-eng",
    platform: "INSTAHYRE",
    sourceLabel: "Instahyre-like job board (demo)",
    title: "Data Engineer",
    company: "QuantLeaf",
    locations: ["Mumbai"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["Python", "SQL", "Kafka"],
    mandatory: ["Python"],
    preferred: ["AWS", "Docker"],
    about: "QuantLeaf builds trading analytics for brokers.",
    responsibilities: ["Build streaming data pipelines", "Maintain data quality checks"],
    apply: { url: "https://demo-instahyre.example/job-2009-data-engineer-at-quantleaf" },
    postedDaysAgo: 11,
  },
  {
    key: "arogya-frontend",
    platform: "GREENHOUSE",
    sourceLabel: "Greenhouse-like career page (demo)",
    title: "Frontend Engineer",
    company: "Arogya Health",
    locations: ["Chennai"],
    workMode: "hybrid",
    yoe: [2, 5],
    required: ["React", "TypeScript", "Web accessibility"],
    preferred: ["React Testing Library", "GraphQL"],
    about: "Arogya Health builds patient and clinic software used across South India.",
    responsibilities: ["Build accessible patient-facing flows", "Collaborate with clinicians on usability"],
    apply: { url: `${LOCAL}/demo/ats/greenhouse/arogya-frontend` },
    postedDaysAgo: 14,
  },
  {
    key: "tuneforge-audio",
    platform: "LEVER",
    sourceLabel: "Lever-like career page (demo)",
    title: "Software Engineer - Audio Editor UI",
    company: "TuneForge",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [2, 6],
    required: ["TypeScript", "React", "Canvas API"],
    preferred: ["Web Workers", "Video editing timelines", "Rendering performance"],
    about: "TuneForge is a browser-based podcast and audio editor for creators.",
    responsibilities: ["Build waveform rendering on canvas", "Implement a multi-track timeline for audio clips"],
    apply: { url: `${LOCAL}/demo/ats/lever/tuneforge-audio` },
    postedDaysAgo: 6,
  },
  {
    key: "govault-angular",
    platform: "NAUKRI",
    sourceLabel: "Naukri-like job board (demo)",
    title: "Angular Developer",
    company: "GoVault Systems",
    locations: ["Pune"],
    workMode: "onsite",
    yoe: [3, 6],
    required: ["Angular", "TypeScript", "RxJS"],
    mandatory: ["Angular"],
    preferred: ["Java"],
    about: "GoVault Systems builds enterprise document management software.",
    responsibilities: ["Maintain Angular enterprise apps", "Integrate with Java backend services"],
    apply: { url: "https://demo-naukri.example/job-listings/govault-angular-developer-3-6-years-1010" },
    postedDaysAgo: 18,
  },
  {
    key: "craftly-fullstack-email",
    platform: "OTHER",
    sourceLabel: "Email-only HR application (demo)",
    title: "Full-Stack Developer",
    company: "Craftly",
    locations: ["Hyderabad"],
    workMode: "hybrid",
    yoe: [2, 5],
    required: ["React", "Node.js", "Express", "PostgreSQL"],
    preferred: ["TypeScript", "Docker"],
    about: "Craftly is a marketplace for handmade products from Indian artisans.",
    responsibilities: ["Build marketplace features end-to-end", "Maintain Express APIs"],
    extras: ["Notice period: up to 30 days preferred."],
    apply: { email: "jobs@craftly.test", instructions: "Email jobs@craftly.test with your resume attached." },
    postedDaysAgo: 5,
  },
  {
    key: "vistara-workday-sde",
    platform: "WORKDAY",
    sourceLabel: "Workday-like career page (demo)",
    title: "SDE 2 - Frontend",
    company: "Vistara Networks",
    locations: ["Bengaluru"],
    workMode: "onsite",
    yoe: [3, 5],
    required: ["JavaScript", "React", "Unit testing", "REST API"],
    preferred: ["TypeScript", "Webpack", "Jest"],
    about: "Vistara Networks builds network management software for telecom operators.",
    responsibilities: ["Build network topology dashboards", "Write unit tests and maintain CI"],
    extras: ["B.Tech/B.E. in Computer Science or related field."],
    apply: { url: `${LOCAL}/demo/ats/workday/vistara-workday-sde` },
    postedDaysAgo: 13,
  },
  {
    key: "inkwell-collab",
    platform: "ASHBY",
    sourceLabel: "Ashby-like career page (demo)",
    title: "Product Engineer - Collaborative Canvas",
    company: "Inkwell",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [3, 7],
    required: ["React", "TypeScript", "Canvas API", "WebSockets"],
    preferred: ["CRDTs", "State management", "Rendering performance"],
    about: "Inkwell is a real-time collaborative whiteboard for product teams.",
    responsibilities: ["Build multiplayer canvas interactions", "Own rendering performance for large boards"],
    apply: { url: `${LOCAL}/demo/ats/ashby/inkwell-collab` },
    postedDaysAgo: 3,
    salaryLpa: [30, 42],
  },
  {
    key: "zapkart-sdet",
    platform: "INDEED",
    sourceLabel: "Indeed-like job board (demo)",
    title: "SDET - Web Automation",
    company: "ZapKart",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [2, 5],
    required: ["Playwright", "TypeScript", "End-to-end testing"],
    preferred: ["Cypress", "CI/CD"],
    about: "ZapKart is a quick-commerce grocery delivery app.",
    responsibilities: ["Build E2E test suites", "Own flaky-test reduction"],
    apply: { url: "https://demo-indeed.example/viewjob?jk=zapkart-sdet-3011" },
    postedDaysAgo: 9,
  },
  {
    key: "motionbase-webgl",
    platform: "COMPANY_CAREER_PAGE",
    sourceLabel: "Company career page (demo)",
    title: "WebGL Engineer",
    company: "MotionBase",
    locations: ["Mumbai", "Remote - India"],
    workMode: "remote",
    yoe: [4, 8],
    required: ["WebGL", "TypeScript", "Rendering performance"],
    mandatory: ["WebGL"],
    preferred: ["Canvas API", "Video editing timelines"],
    about: "MotionBase is a motion graphics creator tool running in the browser.",
    responsibilities: ["Build GPU-accelerated effects", "Optimise the render loop"],
    apply: { url: `${LOCAL}/demo/ats/career/motionbase-webgl` },
    postedDaysAgo: 7,
  },
  {
    key: "helix-devops",
    platform: "INSTAHYRE",
    sourceLabel: "Instahyre-like job board (demo)",
    title: "DevOps Engineer",
    company: "Helix Cloud",
    locations: ["Gurgaon"],
    workMode: "onsite",
    yoe: [3, 7],
    required: ["Kubernetes", "Docker", "AWS", "CI/CD"],
    mandatory: ["Kubernetes"],
    preferred: ["Go"],
    about: "Helix Cloud offers managed Kubernetes for Indian enterprises.",
    responsibilities: ["Operate production clusters", "Automate deployments"],
    apply: { url: "https://demo-instahyre.example/job-2012-devops-engineer-at-helix-cloud" },
    postedDaysAgo: 16,
  },
  {
    key: "saathi-saas-frontend",
    platform: "LEVER",
    sourceLabel: "Lever-like career page (demo)",
    title: "Frontend Developer - SaaS Dashboard",
    company: "Saathi HR",
    locations: ["Bengaluru"],
    workMode: "hybrid",
    yoe: [2, 4],
    required: ["React", "TypeScript", "Complex UI workflows"],
    preferred: ["Redux", "Jest", "Design systems"],
    about: "Saathi HR is an HR and payroll SaaS for Indian startups.",
    responsibilities: ["Build multi-step onboarding and payroll workflows", "Improve dashboard rendering performance"],
    apply: { url: `${LOCAL}/demo/ats/lever/saathi-saas-frontend` },
    postedDaysAgo: 4,
  },
  {
    key: "yatra-ml",
    platform: "NAUKRI",
    sourceLabel: "Naukri-like job board (demo)",
    title: "Machine Learning Engineer",
    company: "YatraMind",
    locations: ["Hyderabad"],
    workMode: "onsite",
    yoe: [4, 8],
    required: ["Python", "Machine learning", "SQL"],
    mandatory: ["Machine learning"],
    preferred: ["LLM integration", "AWS"],
    about: "YatraMind builds travel recommendation systems.",
    responsibilities: ["Train ranking models", "Deploy ML services"],
    apply: { url: "https://demo-naukri.example/job-listings/yatramind-ml-engineer-4-8-years-1013" },
    postedDaysAgo: 22,
  },
  {
    key: "creatorhub-fullstack",
    platform: "GREENHOUSE",
    sourceLabel: "Greenhouse-like career page (demo)",
    title: "Full-Stack Engineer - Creator Tools",
    company: "CreatorHub",
    locations: ["Remote - India"],
    workMode: "remote",
    yoe: [4, 8],
    required: ["React", "TypeScript", "Node.js", "Chunked uploads"],
    preferred: ["Amazon S3", "Media workflows", "Redis"],
    about: "CreatorHub gives creators one place to edit, schedule and publish videos.",
    responsibilities: ["Build upload and publishing pipelines", "Own features across React and Node.js"],
    apply: { url: `${LOCAL}/demo/ats/greenhouse/creatorhub-fullstack` },
    postedDaysAgo: 2,
    salaryLpa: [30, 44],
  },
  {
    key: "bookmyseat-frontend-email",
    platform: "OTHER",
    sourceLabel: "Email-only HR application (demo)",
    title: "Frontend Engineer - Seat Maps",
    company: "SeatSense",
    locations: ["Mumbai"],
    workMode: "hybrid",
    yoe: [3, 6],
    required: ["React", "TypeScript", "SVG", "Canvas API"],
    preferred: ["Rendering performance"],
    about: "SeatSense builds interactive seat-selection maps for events and cinemas.",
    responsibilities: ["Build interactive seat maps with SVG and canvas", "Handle real-time availability updates"],
    screening: ["Are you comfortable working from our Mumbai office 3 days a week?"],
    apply: { email: "talent@seatsense.test", instructions: "Email talent@seatsense.test with your resume and portfolio link." },
    postedDaysAgo: 6,
  },
];
